apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-microservice
  labels:
    app: delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete
  template:
    metadata:
      labels:
        app: delete
    spec:
      containers:
        - name: delete
          image: docker.io/library/delete-microservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
