apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-deployment
spec:
  replicas: 2  # Antal pods att köra
  selector:
    matchLabels:
      app: delete
  template:
    metadata:
      labels:
        app: delete
    spec:
      containers:
        - name: delete
          image: delete:latest  # Namnet på din Docker-image
          ports:
               - targetPort: 4444
               - containerPort: 8080  # Porten som containern lyssnar på